[tools]
node = "22.12.0"

[tasks.test]
run = "npx playwright test"

[tasks.report]
run = "npx playwright show-report"

[tasks.codegen]
run = "npx playwright codegen https://merchandise-dev.odds.team"
